Repository rp-rs/rp-hal, pull requests merged in 2023-05, with the labels that each got.

#611 Fix Spi for EH1 alpha
  rp2040-hal/examples/spi.rs
  rp2040-hal/examples/spi_dma.rs
  rp2040-hal/src/spi.rs
Labels: breaking change

#612 multicore: Fix undefined behaviour in multicore
  rp2040-hal/src/multicore.rs
Labels: minor change

#607 improve usb errata 5 feature's documentation.
  rp2040-hal/Cargo.toml
  rp2040-hal/src/lib.rs
  rp2040-hal/src/usb.rs
  rp2040-hal/src/usb/errata5.rs
Labels: minor change

#614 Cloneable timer
  rp2040-hal/examples/blinky.rs
  rp2040-hal/src/timer.rs
Labels: enhancement

#594 Remove the requirement for multicore tasks to never return
  rp2040-hal/CHANGELOG.md
  rp2040-hal/src/multicore.rs
Labels: breaking change

#598 Upgrade boot2 to version 0.3.0
  on-target-tests/Cargo.toml
  rp2040-hal/CHANGELOG.md
  rp2040-hal/Cargo.toml
Labels: breaking change

#618 Make sure clocks are initialized before creating a Timer
  rp2040-hal/CHANGELOG.md
  rp2040-hal/examples/blinky.rs
  rp2040-hal/examples/vector_table.rs
  rp2040-hal/src/timer.rs
Labels: breaking change

#617 Add several changelog entries
  rp2040-hal/CHANGELOG.md
Labels: documentation

#624 Fix on target tests
  on-target-tests/Cargo.toml
  on-target-tests/tests/dma_spi_loopback_u16.rs
  on-target-tests/tests/dma_spi_loopback_u8.rs
Labels: minor change
