Repository rp-rs/rp-hal, pull requests merged in 2023-11, with the labels that each got.

#709 Mention linker flags in README
  README.md
Labels: documentation

#705 Make i2c::controller pub again
  rp2040-hal/src/i2c.rs
Labels: non-breaking change

#688 Use same USB_PLL default setting as the C SDK
  rp2040-hal/CHANGELOG.md
  rp2040-hal/src/pll.rs
Labels: non-breaking change

#668 Add function to enable multiple PWM slices at the same time
  rp2040-hal/src/pwm/mod.rs
Labels: enhancement, non-breaking change

#584 Update usb-device implementation.
  .github/workflows/build_and_test.yml
  rp2040-hal/CHANGELOG.md
  rp2040-hal/Cargo.toml
  rp2040-hal/src/usb.rs
Labels: breaking change

#716 Revert "Make i2c::controller pub again"
  rp2040-hal/src/i2c.rs
Labels: breaking change

#718 Add a short explanation on how to use RingOscillator as a random number source
  rp2040-hal/Cargo.toml
  rp2040-hal/src/rosc.rs
Labels: documentation, non-breaking change

#676 Add RTC examples & expand RealTimeClock & ClockManager capabilities.
  rp2040-hal/Cargo.toml
  rp2040-hal/examples/rtc_irq_example.rs
  rp2040-hal/examples/rtc_sleep_example.rs
  rp2040-hal/src/clocks/mod.rs
  rp2040-hal/src/rtc/datetime.rs
  rp2040-hal/src/rtc/mod.rs
Labels: breaking change
