Repository rp-rs/rp-hal, pull requests merged in 2023-08, with the labels that each got.

#662 Upate to rp2040-pac version 0.5.0
  .github/workflows/build_and_test.yml
  rp2040-hal/Cargo.toml
  rp2040-hal/src/adc.rs
  rp2040-hal/src/gpio/mod.rs
  rp2040-hal/src/gpio/pin/pin_sealed.rs
  rp2040-hal/src/pio.rs
  rp2040-hal/src/timer.rs
  rp2040-hal/src/usb.rs
Labels: breaking change

#664 Fix an import in a doc comment
  rp2040-hal/src/gpio/mod.rs
Labels: bug

#675 Fix typo in rom_data.rs
  rp2040-hal/src/rom_data.rs
Labels: breaking change

#621 Mark ReadTarget and WriteTarget as unsafe
  rp2040-hal/src/dma/mod.rs
  rp2040-hal/src/pio.rs
  rp2040-hal/src/spi.rs
  rp2040-hal/src/uart/reader.rs
  rp2040-hal/src/uart/writer.rs
Labels: bug, breaking change
