Repository rp-rs/rp-hal, pull requests merged in 2023-07, with the labels that each got.

#609 Fix broken link to team list
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#602 Actually build on-target-tests in CI
  .github/workflows/build_and_test.yml
Labels: minor change

#636 ADC fifo DMA
  rp2040-hal/Cargo.toml
  rp2040-hal/examples/adc_fifo_dma.rs
  rp2040-hal/examples/adc_fifo_irq.rs
  rp2040-hal/src/adc.rs
Labels: enhancement, breaking change

#646 Implement WriteTarget for PWM top and cc registers.
  rp2040-hal/src/pwm/mod.rs
Labels: enhancement, non-breaking change

#571 Upgrade syn to version 2.0
  rp2040-hal-macros/Cargo.toml
Labels: non-breaking change

#651 Migrate rp2040-hal to edition 2021
  rp2040-hal/Cargo.toml
  rp2040-hal/src/adc.rs
  rp2040-hal/src/clocks/macros.rs
  rp2040-hal/src/clocks/mod.rs
  rp2040-hal/src/dma/mod.rs
  rp2040-hal/src/dma/single_channel.rs
  rp2040-hal/src/float/div.rs
  rp2040-hal/src/gpio/mod.rs
  rp2040-hal/src/gpio/pin.rs
  rp2040-hal/src/gpio/pin/pin_sealed.rs
  rp2040-hal/src/i2c.rs
  rp2040-hal/src/i2c/controller.rs
  rp2040-hal/src/i2c/peripheral.rs
  rp2040-hal/src/lib.rs
  rp2040-hal/src/pio.rs
  rp2040-hal/src/pll.rs
  rp2040-hal/src/pwm/mod.rs
  rp2040-hal/src/pwm/reg.rs
  rp2040-hal/src/resets.rs
  rp2040-hal/src/rosc.rs
  rp2040-hal/src/rtc/datetime_chrono.rs
  rp2040-hal/src/rtc/datetime_no_deps.rs
  rp2040-hal/src/rtc/filter.rs
  rp2040-hal/src/rtc/mod.rs
  rp2040-hal/src/spi.rs
  rp2040-hal/src/spi/pins.rs
  rp2040-hal/src/timer.rs
  rp2040-hal/src/uart/peripheral.rs
  rp2040-hal/src/uart/reader.rs
  rp2040-hal/src/uart/utils.rs
  rp2040-hal/src/uart/writer.rs
  rp2040-hal/src/usb.rs
  rp2040-hal/src/usb/errata5.rs
  rp2040-hal/src/vector_table.rs
  rp2040-hal/src/watchdog.rs
  rp2040-hal/src/xosc.rs
Labels: non-breaking change

#645 Use fixed version nightly-2023-06-27 for cargo udeps
  .github/workflows/build_and_test.yml
Labels: non-breaking change
